import './Footer.css';

export default function Footer({ isReaderPage = false }) {
  // Hide footer on reader page (both mobile and desktop)
  if (isReaderPage) {
    return null;
  }

  return (
    <footer className="app-footer">
      <p>
        Mocking a poem every ten minutes{' '}
        <a 
          href="https://mockpoet.tumblr.com/" 
          target="_blank" 
          rel="noopener noreferrer"
          className="footer-link"
        >
          @mockpoet
        </a>
        {' | '}Generated by AI
      </p>
    </footer>
  );
}
