import jsPDF from 'jspdf';

/**
 * Generate PDF from chapters
 * @param {string} bookTitle - Title of the book
 * @param {Array} chapters - Array of chapter objects with content
 */
export function generatePDF(bookTitle, chapters) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Set standard ebook font
  doc.setFont('times', 'normal');
  doc.setFontSize(12);

  // Title page
  doc.setFontSize(20);
  doc.setFont('times', 'bold');
  const titleLines = doc.splitTextToSize(bookTitle, maxWidth);
  doc.text(titleLines, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += titleLines.length * 10 + 20;
  
  doc.setFontSize(10);
  doc.setFont('times', 'italic');
  doc.text('Generated by AI', pageWidth / 2, yPosition, { align: 'center' });
  
  // Add chapters
  chapters.forEach((chapter, index) => {
    doc.addPage();
    yPosition = margin;
    
    // Chapter title
    doc.setFontSize(16);
    doc.setFont('times', 'bold');
    const chapterTitle = chapter.title || `Chapter ${index + 1}`;
    const titleHeight = doc.splitTextToSize(chapterTitle, maxWidth);
    doc.text(titleHeight, margin, yPosition);
    yPosition += titleHeight.length * 8 + 10;
    
    // Published date if available
    if (chapter.publishedDate) {
      doc.setFontSize(9);
      doc.setFont('times', 'italic');
      const date = new Date(chapter.publishedDate).toLocaleString();
      doc.text(`Published: ${date}`, margin, yPosition);
      yPosition += 8;
    }
    
    yPosition += 5;
    
    // Chapter content
    doc.setFontSize(12);
    doc.setFont('times', 'normal');
    
    // Convert HTML to plain text
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = chapter.content;
    const plainText = tempDiv.textContent || tempDiv.innerText || '';
    
    // Split text into paragraphs
    const paragraphs = plainText.split(/\n\n+/);
    
    paragraphs.forEach(paragraph => {
      const lines = doc.splitTextToSize(paragraph.trim(), maxWidth);
      
      lines.forEach(line => {
        if (yPosition > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin, yPosition);
        yPosition += 7;
      });
      
      yPosition += 5; // Space between paragraphs
    });
  });

  // Save the PDF
  const filename = `${bookTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`;
  doc.save(filename);
}

/**
 * Generate simplified EPUB HTML from chapters
 * Note: This creates a simplified HTML file that can be read in browsers
 * For a full EPUB package, consider using a dedicated library
 * @param {string} bookTitle - Title of the book
 * @param {Array} chapters - Array of chapter objects with content
 */
export function generateEPUB(bookTitle, chapters) {
  // Create EPUB HTML content
  const content = generateEPUBHTML(bookTitle, chapters);
  
  // Create a blob and download
  const blob = new Blob([content], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${bookTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generate EPUB-style HTML content
 * Creates a well-formatted HTML document suitable for reading
 */
function generateEPUBHTML(bookTitle, chapters) {
  let html = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>${escapeXml(bookTitle)}</title>
  <style>
    body {
      font-family: "Georgia", "Times New Roman", serif;
      font-size: 12pt;
      line-height: 1.6;
      margin: 2em;
    }
    h1 {
      font-size: 1.8em;
      margin-top: 2em;
      margin-bottom: 0.5em;
      page-break-before: always;
    }
    h2 {
      font-size: 1.4em;
      margin-top: 1.5em;
      margin-bottom: 0.5em;
    }
    p {
      text-align: justify;
      margin-bottom: 1em;
    }
    .title-page {
      text-align: center;
      padding: 4em 0;
    }
    .chapter-date {
      font-style: italic;
      font-size: 0.9em;
      color: #666;
      margin-bottom: 1em;
    }
    .footer {
      text-align: center;
      font-style: italic;
      font-size: 0.9em;
      margin-top: 2em;
      color: #666;
    }
  </style>
</head>
<body>
  <div class="title-page">
    <h1>${escapeXml(bookTitle)}</h1>
    <p class="footer">All text content is generated by AI</p>
  </div>
`;

  chapters.forEach((chapter, index) => {
    const chapterTitle = chapter.title || `Chapter ${index + 1}`;
    html += `\n  <div class="chapter">\n`;
    html += `    <h1>${escapeXml(chapterTitle)}</h1>\n`;
    
    if (chapter.publishedDate) {
      const date = new Date(chapter.publishedDate).toLocaleString();
      html += `    <p class="chapter-date">Published: ${escapeXml(date)}</p>\n`;
    }
    
    // Convert HTML content to proper XHTML
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = chapter.content;
    const cleanedContent = tempDiv.innerHTML
      .replace(/<p>/g, '    <p>')
      .replace(/<\/p>/g, '</p>\n');
    
    html += cleanedContent;
    html += `  </div>\n`;
  });

  html += `</body>\n</html>`;
  return html;
}

function escapeXml(text) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
